#!/bin/bash

if ! test -d "./dist"; then
  mkdir ./dist
fi

echo ""
echo "http://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html"
echo ""

./jspm build src/main.js dist/bundle.js --minify

./run-gulp build
